#!/bin/sh
#
### BEGIN INIT INFO
# Provides: xserver
# Required-Start: $local_fs $remote_fs dbus
# Required-Stop: $local_fs $remote_fs
# Default-Start:     5
# Default-Stop:      0 1 2 3 6
### END INIT INFO


. /etc/init.d/functions

case "$1" in
  start)
	/home/root/demo-pop-streaming/launchDemo.sh&
  ;;


  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
